### ISSUE TITLE
Suggestion: Expand to NRW, DE

### ISSUE THREAD

**Issue by AndiH** [mrtopf/oecherinfo#1]
I fear that is no easy feat, but extending the dashboard to data from NRW and whole Germany would be great. I think there is no dashboard of similar quality and overview for these respective higher communal levels…

**Comment by mrtopf** [comment]
well, of course I though about it (esp. when looking for numbers for a certain location). 

But my free time is limited and I am not sure if there even is an easy to use API with historical data. So I doubt it will happen in the foreseeable future (at least from me). 

(I even have to enter some data manually at the moment like quicktests so that also adds up in time).

**Comment by AndiH** [comment]
Ok, I see! I also don't have the time. I'll close the issue! (While adding the next one… ;) )
